name: Test Setup Queue Set
# Tests setup-queue-set action

on:
  push:

jobs:
  test_clearcase:
    runs-on: rise
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: 3.8