name: Check depedndabot scan
on:
  issues:
    types: [opened]
    
jobs:
  make-a-scan:
    runs-on: rise
    steps: 
    - uses: peter-murray/workflow-application-token-action@6a9741bf210c9a93370560585c908161170ecada # v2.1.0
      if: ${{ vars.use_github_app == 'true' }}
      id: get-workflow-token
      with:
        application_id: ${{ secrets.GH_AUTOMATION_ID }}
        application_private_key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY }}

    - id: get-token
      env: 
        github_app_token: ${{ steps.get-workflow-token.outputs.token }}
        PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
      run: |
        if [ -n $github_app_token ]; then
          echo "token=$github_app_token" >> $GITHUB_OUTPUT
          echo "Using token from GitHub App"
        else
          echo "token=$PAT_GITHUB" >> $GITHUB_OUTPUT
          echo "Using personal access token from secret 'PAT_GITHUB'"
        fi  

    - id: dependabot-scan
      run: echo ${{github.event.issue.comments}}
      
