name: Send New Actions update Alert on Teams

on:
  issues:
    types: [opened,labeled]
    

permissions:
  issues: write
  contents: read

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo 
      uses: actions/checkout@v3
    
    - uses: asml-actions/ms-teams-notification@main
      with: 
        title: "Issue [${{ github.event.action }}]: '${{ github.event.issue.title }}'"
        text: "New Github Action update (# ${{ github.event.issue.number }}) [${{ github.event.action }}] in asml-actions/github-fork-updater repo by [${{ github.event.issue.user.login }}]"
        button_text: 'Go to the Update'
        url: "${{ github.event.issue.html_url }}"
        #teams_webhook_url: ${{ secrets.TEST_TEAMS_WEBHOOK_URL }} # Testing channel in RISE
        teams_webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }} # GitHub Operational Alerts channel in Greenhouse
      
