name: Validate parent of fork

on:
  push:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read
env:
    fork-owner: GetTuh
    repo-name: json-to-file       
    org: asml-actions-validation
    original-owner: devops-actions
    
    

jobs:
  validate-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - uses: peter-murray/workflow-application-token-action@6a9741bf210c9a93370560585c908161170ecada # v2.1.0
        name: Get token from GitHub App for validation
        id: get-validation-token
        with:
          application_id: ${{ secrets.VALIDATION_APP_ID }}
          application_private_key: ${{ secrets.VALIDATION_APP_TOKEN }}
          organization: asml-actions-validation 

      - name: Run the checks
        run: |
            npm install @octokit/rest
            node code-scan.js  ${{steps.get-validation-token.outputs.token}} ${{env.repo-name}} ${{env.original-owner}}
