name: Validate parent of fork

on:
  push:
    branches:
      - noLanguagesFix

permissions:
  issues: write
  contents: read

jobs:
  validate-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - uses: peter-murray/workflow-application-token-action@6a9741bf210c9a93370560585c908161170ecada # v2.1.0
        name: Get token from GitHub App for validation
        id: get-validation-token
        with:
          application_id: ${{ secrets.VALIDATION_APP_ID }}
          application_private_key: ${{ secrets.VALIDATION_APP_TOKEN }}
          organization: ${{vars.VALIDATION_ORG}}

      - uses: peter-murray/workflow-application-token-action@6a9741bf210c9a93370560585c908161170ecada # v2.1.0
        name: Get token from GitHub App for validation
        id: get-app-token
        with:
          application_id: ${{ secrets.GH_AUTOMATION_ID }}
          application_private_key: ${{ secrets.GH_AUTOMATION_PRIVATE_KEY }}
      
      - name: Get issue details
        id: get_issue_details
        uses: actions/github-script@v6
        with:
          script: |
            const issue_id = 247
            const issue_title = 'Parent repository for [asml-actions/dependabot-action] has updates available'
            const repo_name = issue_title.substring(issue_title.indexOf("/") + 1,  issue_title.lastIndexOf("]"));
            let repoData =await github.rest.repos.get({
              owner: 'asml-actions',
              repo: repo_name
            });
            originalOwner = repoData.data.parent.owner.login
            console.log(`Issue Details - ${issue_id} , ${issue_title}, ${repo_name}`)
            core.setOutput(`repo-name`,repo_name)
            core.setOutput(`original-owner`,originalOwner)

      - name: Run the checks
        id: check-run
        run: |
            npm install @octokit/rest @actions/core
            node src/code-scan.js  ${{steps.get-validation-token.outputs.token}} ${{steps.get_issue_details.outputs.repo-name}} ${{steps.get_issue_details.outputs.original-owner}} ${{vars.VALIDATION_ORG}} 247 ${{steps.get-app-token.outputs.token}} }

      - name: Update the issue
        uses: actions/github-script@v6
        env:
            can_merge: ${{ steps.check-run.outputs.can-merge }}
        with:
          github-token: ${{steps.get-app-token.outputs.token}}
          script: |
            const label  = process.env.can_merge
            console.log(`adding label ${label}`)
      
            github.rest.issues.addLabels({
              owner: 'asml-actions',
              repo: 'dependabot-action',
              issue_number: 247,
              labels: [`${label}`]
            })
